### PR TITLE
Fix compilation for FreeBSD

### PR DESCRIPTION
**Pull request by davidkna**

### CODE REVIEW

**Review by stanislav-tkach — APPROVED** [review]
Thanks!

**Comment by stanislav-tkach** [comment]
I would like to release a new version with this fix (https://github.com/stanislav-tkach/os_info/pull/259), but I have also made some refactoring along the way. Could you please check the release branch?

**Comment by davidkna** [comment]
@stanislav-tkach Now it complains about `uname` being private in `freebsd/mod.rs`.

**Comment by stanislav-tkach** [comment]
@davidkna Thanks! I have fixed that.

**Comment by davidkna** [comment]
By the way [cross](https://github.com/rust-embedded/cross) supports FreeBSD if you add a `Cross.toml` with:
```toml
[target.x86_64-unknown-freebsd]
image = "docker.io/rustembedded/cross:x86_64-unknown-freebsd"
```

**Comment by davidkna** [comment]
@stanislav-tkach It seems to work and compile fine now.

**Comment by stanislav-tkach** [comment]
@davidkna Thanks. I  have released the `3.0.3` version.

**Pull request merged**
