### PR TITLE
Better cross platform support for bitness and NetBSD support

### PR DESCRIPTION
**Pull request by martintc**
In reference to issue #272.

Not all Operating systems support reading from getconf with the argument of "LONG_BIT," NetBSD is one. So instead of making a call out to a CLI tool, using the compiler's configuration with cfg to get the bitness of the target platform being compiled for. Has been tested on NetBSD (see screenshot), FreeBSD, DragonflyBSD, and Linux.

os_info

Included is also files and changed for NetBSD support provided by Kraileth as noted in the commit logs.

### CODE REVIEW

**Comment by martintc** [comment]
Moved the global constants inside of function, hope this will clear up some of the warnings from checks that were ran.

**Comment by martintc** [comment]
os_info_windows

Since the change to pull the declaration of VAL into local scope, it runs wine when tested on Windows 64-bit MSVC. I did not test before, it just looked as if the github actions had issue running it with VAL not in local scope of the get_bitness function

**Comment by stanislav-tkach** [comment]
Sorry for the terribly late reply and thanks for the pull request!

I have some concerns about `target_pointer_width`. Isn't it possible to (cross)compile the application for 32 bit and then run it on the 64 bit OS? In that case such solution gives us `Bitness::X32` and not the actual operating system bitness.

**Comment by martintc** [comment]
> Sorry for the terribly late reply and thanks for the pull request!
> 
> I have some concerns about `target_pointer_width`. Isn't it possible to (cross)compile the application for 32 bit and then run it on the 64 bit OS? In that case such solution gives us `Bitness::X32` and not the actual operating system bitness.

The new changes should address this. Instead of relying on compile time variables, this new implementation uses the size_of in std::mem to test the size of the usize type. According to rust documents, the size of usize should return the size of addressable memory location on a given platform. 

Reference:
https://doc.rust-lang.org/std/primitive.usize.html

**Comment by martintc** [comment]
So, working with someone who is more familiar with Rust than I am, here is a conclusion we came to after also attempting some other possibilites. With this implementation, it still determines the size of `usize` during compile time, it hard codes it into a data section in the assembly. Trying some other potential ways, the result was the same. The Rust compiler, during optimization, is going to take the size of `usize` on the compiled environment and hard code it into the binary. Here is an example of the output assembly using a similar representation as to what is in this PR.

```rust
example::main:
        sub     rsp, 56
        lea     rax, [rip + .L__unnamed_1]
        mov     qword ptr [rsp + 8], rax
        mov     qword ptr [rsp + 16], 1
        mov     qword ptr [rsp + 24], 0
        lea     rax, [rip + .L__unnamed_2]
        mov     qword ptr [rsp + 40], rax
        mov     qword ptr [rsp + 48], 0
        lea     rdi, [rsp + 8]
        call    qword ptr [rip + std::io::stdio::_print@GOTPCREL]
        add     rsp, 56
        ret

.L__unnamed_2:

.L__unnamed_3:
        .ascii  "64 bits\n"

.L__unnamed_1:
        .quad   .L__unnamed_3
        .asciz  "\b\000\000\000\000\000\000"
```

**Comment by stanislav-tkach** [comment]
Sorry, I have disappeared again. You are right: the size of `usize` and `isize` types are determined at the compile time.

**Pull request closed without merging**
