### PR TITLE
Add support for Windows Server 2019 using ProductName

### PR DESCRIPTION
**Pull request by Coding-Badly**
This is an alternative that favours `ProductName` from the Registry for `edition`.

### CODE REVIEW

**Review by stanislav-tkach — COMMENTED** [review]
I really like this version more. :upside_down_face: 

What do you think about using `RegOpenKeyExA` and other `___A` functions though?

**Comment by Coding-Badly** [comment]
I have not dug into the details so I don't know how accurate the following is.

My understanding is that the ANSI functions use the system code page.  For example, if I have Scottish Gaelic enabled for my desktop then run a program that program runs with the Windows-28604 code page.  The ANSI `RegQueryValueExA` returns the string converted to the system code page (e.g. Scottish Gaelic).  To be usable in Rust that string has to be converted to UTF-8.  There are Windows calls to perform that sort of translation.  So, we would get a string in a particular code page, read the current system code page, call a function to translate the string, then have something that works for Rust.

According to [this](https://devblogs.microsoft.com/oldnewthing/20100603-00/?p=13823) converting from Unicode to ANSI / code page back to Unicode is lossy.  If it is we're much better served converting from dirty UTF-16 to clean UTF-8 where the only loss will be rare invalid characters.

In any case, I believe using the ANSI functions adds a few more confusing API calls.  In contrast, using the widestring calls is mostly buffer management with a little Rust (e.g. the single `from_wide` call handles the UTF conversion).

**Comment by Coding-Badly** [comment]
I really like this one as well.

**Comment by stanislav-tkach** [comment]
> My understanding is that the ANSI functions use the system code page.

Makes sense, but isn't the edition only represented by ASCII string? In that case we can usea  simple conversion ignoring the code page entirely.

As for trailing null it can be added using byte-strings: `b"SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\0"`.

**Comment by Coding-Badly** [comment]
> Makes sense, but isn't the edition only represented by ASCII string?

Ah, if only.

Some things to consider...
* As far as I know Microsoft has never made that claim.  Their marketing department could decide that, being 50 years since Microsoft was founded, the 2025 release should have an extra special name.  `Windows Siècle` seems like a a good choice; as in "Windows for the century".
* It's a plain old Registry value.  Nothing prevents someone from changing.  For example, I've seen hardware manufactures put their name in front of things.  They could label a customized edition "Lenovo Windows 10".  Which is still OK until a Chinese manufacturer decides to customize their edition for the Chinese market and labels it "最好的 Windows 10".
* Nothing prevents an end user from changing the Registry value.

**Comment by stanislav-tkach** [comment]
You have managed to convince me. :upside_down_face:

**Review by stanislav-tkach — APPROVED** [review]

**Comment by Coding-Badly** [comment]
Cool.  Thanks!

**Pull request merged**
