### PR TITLE
Fix: Add Types for Ultramarine Linux

### PR DESCRIPTION
**Pull request by 8bitZeta**
I completely forgot to add the Types for Ultramarine on my previous PR. This should rectify that.

### CODE REVIEW

**Review by ydirson — CHANGES_REQUESTED** [review]
Please have a look at the jobs still failing  ;)

**Comment by 8bitZeta** [comment]
> Please have a look at the jobs still failing ;)

Yup, I have a few changes on my end addressing these, and I'm stuck on one snag currently.

Hoping to have it fixed before the day is over.

**Comment by 8bitZeta** [comment]
@ydirson, almost everything seems to be passing sans a Windows issue which is being addressed in another PR via Dependabot...

Are you able to test/build now?

**Review by ydirson — COMMENTED** [review]
just a few remarks about commit structuring, otherwise lgtm

**Review by stanislav-tkach — APPROVED** [review]

**Pull request merged**
