### PR TITLE
Fix: issue #300

### PR DESCRIPTION
**Pull request by martintc**
Replace unwrapping the various ouputs with using the Result types

### CODE REVIEW

**Comment by stanislav-tkach** [comment]
Sorry for the late reply! Is there something wrong with the pull request? Could you please reopen it?

**Comment by stanislav-tkach** [comment]
Oh, sorry. Now I see that there is another pull request (https://github.com/stanislav-tkach/os_info/pull/303).

**Comment by martintc** [comment]
> Oh, sorry. Now I see that there is another pull request (https://github.com/stanislav-tkach/os_info/pull/303).

It's alright. Does the code in the PR look like what you had in mind?

**Comment by martintc** [comment]
Oh yea, I opened this PR then realized I was working off an old branch, so I closed it, updated my local copies with main and put the fixes in a new branch leading to PR #303.

**Pull request closed without merging**
