### PR TITLE
Add openEuler and OpenCloudOS support

### PR DESCRIPTION
**Pull request by leavelet**
Add openEuler and OpenCloudOS support. I have tested them and it works well.

### CODE REVIEW

**Comment by exincore** [comment]
Hello! Since you seem to have the os-release files on-hand, could you add them into respective folders in `src/linux/tests/` and create tests in `src/linux/file_release.rs`?

**Comment by leavelet** [comment]
Did I add these tests correctly?

**Comment by exincore** [comment]
The tests look good to me!

**Review by stanislav-tkach — APPROVED** [review]
Thank you for the pull request!

**Pull request merged**
